#!/bin/bash
#
# Jordan Hrenyk, December 11th/2018
#
# Used in a Laptop with both a Intel iGPU and Nvidia GPU.
# Root Access is required to run the prime-select command and a 
# Log out and back in is required to apply the changes.

GPU=$(prime-select query)
USER=$(whoami)

# Switch from nvidia to intel
if [[ "${GPU}" = nvidia ]]
	then
		sudo prime-select intel
		echo "Switching to Intel"
		
		if [[ ${GPU} = intel ]]
		then	
			echo "Switch completed"
			sudo undervolt --core -160 --cache -160 --gpu -70
			loginctl terminate-user "$USER"
			exit 0
		else
			sudo prime-select nvidia
			echo " Unable to switch to intel GPU"
			exit 1
		fi
fi

# Switch from intel to nvidia
if [[ "${GPU}" = intel ]] 
	then
		sudo prime-select nvidia
		echo "Switching to Nvidia"
		
		if [[ ${GPU} = nvidia ]]
		then
			echo "Switch completed"
			sudo undervolt --core -145 --cache -145 --gpu -65
			loginctl terminate-user "$USER"
			exit 0
		else
			echo " Unable to switch to nvidia GPU"
			sudo prime-select intel
			exit 1
		fi

fi

exit 0

