#!/bin/bash
#
# Jordan Hrenyk, December 11th/2018
#
# Used in a Laptop with both a Intel iGPU and Nvidia GPU.
# Root Access is required to run the prime-select command and a 
# Log out and back in is required to apply the changes.

GPU=$(prime-select query)
USER=$(whoami)

# Switch from nvidia to intel
if [ "${GPU}" = nvidia ]
	then
		sudo prime-select intel
		echo "Switching to Intel"
fi

# Switch from intel to nvidia
if [ "${GPU}" = intel ]
	then
		sudo prime-select nvidia
		echo "Switching to Nvidia"

fi

# Logout user

if [ "${?}" = 0 ]
	then
		loginctl terminate-user "$USER"
	fi
exit 0
